program: /mnt/home/f0106093/Projects/multiomics-embedding/src/sweep.py
name: multiomics
method: grid
metric:
  name: val_balanced_accuracy_avg
  goal: maximize
parameters:
  p:
    values: [0.01, 0.1, 1, 10, 100]
  q:
    values: [0.01, 0.1, 1, 10, 100]
  g:
    values: [0.0]
  penalty:
    values: ["l1", "l2"]
  c:
    values: [0.1, 1, 10, 100, 1000]
command:
- python
- ${program}
# specify the fold 
# idealy need to make this dynamic
- --fold
- 1
- --n2v
- Pre
- ${args}

