command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_q_7.078691990493878
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_sweep
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 20
    min: 0.1
  q:
    values:
    - 6.578691990493878
    - 6.9786919904938784
    - 7.078691990493878
    - 7.178691990493878
    - 7.578691990493878
program: src/sweep.py
