command:
- python
- ${program}
- --fold
- 1
- --n2v
- Pre
- ${args}
method: grid
metric:
  goal: maximize
  name: val_balanced_accuracy_avg
name: multiomics-fold-1
parameters:
  c:
    values:
    - 0.0001
    - 0.001
    - 0.01
    - 0.1
  g:
    values:
    - 1
  p:
    values:
    - 0.01
    - 0.1
    - 1
    - 10
    - 100
  penalty:
    values:
    - l1
    - l2
  q:
    values:
    - 0.01
    - 0.1
    - 1
    - 10
    - 100
program: src/sweep.py
