command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- diet_classifier
- ${args}
method: random
metric:
  goal: maximize
  name: diet_avg_val_f1
name: diet_classifier
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 50
    min: 0.5
  q:
    distribution: uniform
    max: 20
    min: 0.1
program: src/sweep.py
