command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_p_50
- --seed
- '30'
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_p_50
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    values:
    - 49.5
    - 50
    - 50.5
  q:
    distribution: uniform
    max: 10
    min: 0.1
program: src/sweep.py
