command:
- python
- ${program}
- --fold
- 5
- --n2v
- OTF
- ${args}
- --sweep
- 20240926_multiomics_model_5
method: grid
metric:
  goal: maximize
  name: f1_val_avg
name: 20240926_multiomics_model_5
parameters:
  c:
    values:
    - 10
    - 25
    - 40
    - 50
    - 75
    - 90
    - 100
    - 200
    - 300
    - 400
    - 500
  filter:
    values:
    - from_adelle
  g:
    values:
    - 0
    - 1
    - 2
  p:
    values:
    - 0.5
    - 1
    - 10
    - 50
  penalty:
    values:
    - l2
  q:
    values:
    - 0.5
    - 1
    - 10
    - 50
program: src/sweep.py
