command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- multiomics_embedding
- ${args}
method: random
metric:
  goal: maximize
  name: emb_score
name: multiomics_embedding
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: int_uniform
    max: 25
    min: 1
  q:
    distribution: uniform
    max: 10
    min: 0.1
program: src/sweep.py
