command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_q_3.818854151367598
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_sweep
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 20
    min: 0.1
  q:
    values:
    - 3.318854151367598
    - 3.718854151367598
    - 3.818854151367598
    - 3.918854151367598
    - 4.3188541513675975
program: src/sweep.py
