command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_p_18.76305677654519
- --seed
- '30'
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_p_18.76305677654519
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    values:
    - 18.26305677654519
    - 18.76305677654519
    - 19.26305677654519
  q:
    distribution: uniform
    max: 10
    min: 0.1
program: src/sweep.py
