command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_q_5.219434543005656
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_sweep
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 20
    min: 0.1
  q:
    values:
    - 4.719434543005656
    - 5.1194345430056565
    - 5.219434543005656
    - 5.319434543005656
    - 5.719434543005656
program: src/sweep.py
