command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_q_0.1
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_sweep
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 20
    min: 0.1
  q:
    values:
    - 0.1
    - 0.1
    - 0.1
    - 0.2
    - 0.6
program: src/sweep.py
