command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- p_19
- --seed
- '30'
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: p_19
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    values:
    - 18.5
    - 19
    - 19.5
  q:
    distribution: uniform
    max: 10
    min: 0.1
program: src/sweep.py
