command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_q_3.901922405213064
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_sweep
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 20
    min: 0.1
  q:
    values:
    - 3.401922405213064
    - 3.801922405213064
    - 3.901922405213064
    - 4.0019224052130635
    - 4.401922405213064
program: src/sweep.py
