command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_q_0.946419088343395
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_sweep
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 20
    min: 0.1
  q:
    values:
    - 0.44641908834339505
    - 0.8464190883433951
    - 0.946419088343395
    - 1.046419088343395
    - 1.446419088343395
program: src/sweep.py
