command:
- python
- ${program}
- --n2v
- OTF
- --sweep
- stability_sweep
- ${args}
method: random
metric:
  goal: maximize
  name: f1
name: stability_sweep
parameters:
  g:
    values:
    - 0
    - 1
    - 2
  p:
    distribution: uniform
    max: 20
    min: 0.1
  q:
    values:
    - 3.9083364610918743
    - 4.308336461091875
    - 4.408336461091874
    - 4.508336461091874
    - 4.908336461091874
program: src/sweep.py
